name: Release mosdns-x

on:
  workflow_dispatch:

jobs:

  build-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24
          check-latest: true
          cache: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build
        run: |
          echo "TAG_NAME=v$(date +'%y.%m.%d')" >> "$GITHUB_ENV"
          python ./release.py
        env:
          CGO_ENABLED: '0'
          TZ: Asia/Hong_Kong

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          name: Mosdns-x ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: './release/mosdns*.zip'
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
